[server]
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200
maxMessageSize = 200

[client]
showErrorDetails = false

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"
serverPort = 8501
